name: streaming_gen_ui
description: "A high-performance streaming Generative UI engine for Flutter. Render interactive components reactively as raw LLM streams flow in character-by-character."
version: 0.1.0
repository: https://github.com/ComsIndeed/streaming-gen-ui

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  llm_json_stream: ^1.0.0
  llm_tag_parser: ^0.1.1
  # llm_json_stream:
  #   path: "../_TEMPORARY_/llm_json_stream_dart"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
