name: streaming_gen_ui_widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  llm_json_stream: ^1.0.0
  dartantic_ai: ^3.4.0
  streaming_gen_ui:
    path: "../"
  gpt_markdown: ^1.1.7
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path: ^1.9.1

flutter:
  uses-material-design: true
