name: streaming_gen_ui_widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  llm_json_stream: ^0.4.7
  streaming_gen_ui:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
